apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deployment.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: logger-service
  name: logger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logger-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-deployment.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: logger-service
    spec:
      containers:
        - image: qonicsinc/swiftqom-logger-service:1.0.0
          name: logger-service
      restartPolicy: Always
      imagePullSecrets:
        - name: qonicsinc-dockerhub
