apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deployment.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: krakend
  name: krakend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: krakend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-deployment.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: krakend
    spec:
      containers:
        - image: devopsfaith/krakend
          name: krakend
          ports:
            - containerPort: 8090
              protocol: TCP
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          env:
          - name: KRAKEND_PORT
            value: "8090"
          volumeMounts:
            - name: krakend-config-volume
              mountPath: /etc/krakend
      restartPolicy: Always
      volumes:
        - name: krakend-config-volume
          hostPath:
            path: /root/resources/lottery/
            type: Directory  # Specify that it's a file, you can use "Directory" if it's a directory
