apiVersion: v1
kind: Service
metadata:
  name: krakend
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deployment.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: krakend
spec:
  type: NodePort
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
      nodePort: 30081  # You can choose a port in the range 30000-32767
  selector:
    io.kompose.service: krakend