apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: localdriver
  name: localdriver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
