apiVersion: v1
kind: PersistentVolume
metadata:
  name: lottery-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/lottery-pv1
