apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv3
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  # storageClassName: localdriver
  hostPath:
    path: /data/pg-pv3
